### ISSUE TITLE
Error while parsing

### ISSUE THREAD

**Issue by twenzel** [devlooped/dotnet-trx#31]
## Error while parsing

```
Unhandled exception. System.InvalidOperationException: Unbalanced markup stack. Did you forget to close a tag?
   at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 55
   at Spectre.Console.Markup..ctor(String text, Style style) in /_/src/Spectre.Console/Widgets/Markup.cs:line 42
   at Spectre.Console.FallbackStatusRenderer.Update(ProgressContext context) in /_/src/Spectre.Console/Live/Progress/Renderers/FallbackStatusRenderer.cs:line 27
   at Spectre.Console.ProgressContext.Refresh() in /_/src/Spectre.Console/Live/Progress/ProgressContext.cs:line 177
   at Spectre.Console.ProgressRefreshThread.Run() in /_/src/Spectre.Console/Live/Progress/ProgressRefreshThread.cs:line 45

```

## Version Info

0.4.1

**Comment by kzu** [comment]
Could you please attach the trx file(s) that generated this?

**Comment by kzu** [comment]
Plz try latest version, reopen with more info if it still happens. Thanks!
