### ISSUE TITLE
System.InvalidOperationException: Unbalanced markup stack

### ISSUE THREAD

**Issue by alexaka1** [devlooped/dotnet-trx#63]
## Describe the Bug

I am encountering the same issue as in #31.

## Steps to Reproduce
In repo https://github.com/alexaka1/serilog-extensions/tree/feature/trx-logger on the trx-logger branch, see the `Tests` action workflow.

## Exception with Stack Trace

```text
Unhandled exception. System.InvalidOperationException: Unbalanced markup stack. Did you forget to close a tag?
   at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 55
   at Spectre.Console.Markup..ctor(String text, Style style) in /_/src/Spectre.Console/Widgets/Markup.cs:line 42
   at Spectre.Console.FallbackStatusRenderer.Update(ProgressContext context) in /_/src/Spectre.Console/Live/Progress/Renderers/FallbackStatusRenderer.cs:line 27
   at Spectre.Console.ProgressContext.Refresh() in /_/src/Spectre.Console/Live/Progress/ProgressContext.cs:line 177
   at Spectre.Console.ProgressRefreshThread.Run() in /_/src/Spectre.Console/Live/Progress/ProgressRefreshThread.cs:line 45
```

## Version Info

0.4.5

## Additional Info
The workflow of this branch uploads the TRX files as an artifact for investigation.
https://github.com/alexaka1/serilog-extensions/actions/runs/12088363249

One of my tests outputs a lot of text to the `ITestOutputHelper`, maybe that is what's causing the issue.

[![Back this issue](https://raw.githubusercontent.com/devlooped/SponsorLink/main/docs/assets/img/separator.png "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)
[![Back this issue](https://img.shields.io/badge/backed-%240-EA4AAA?logo=githubsponsors "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)

**Comment by kzu** [comment]
Should be fixed by https://github.com/devlooped/dotnet-trx/pull/66
